#+title:  pdf-chatbot: Read and chat with PDF documents

* PDF-Chatbot with Mind Map Generation
PDF-chatbot for scientific articles with knowledge graph generation.

** Current Features
- PDF Interaction: Upload your own PDFs or select from a preloaded library.
- RAG-Based Responses: Accurate and contextually relevant answers using a retrieval-assisted generation.
- Mind Map Generation: Visual representation of conversation topics and concepts.

** Installation and Usage
1. Clone the repository.
2. Install the required dependencies.
3. Add OPENAI_API_KEY="" to a .env file
4. Run the Streamlit app.

#+begin_src sh
  git clone https://github.com/yourusername/pdf-chatbot.git
  cd pdf-chatbot
  pip install -r requirements.txt
  streamlit run app.py
#+end_src

** Project Status
- Improve pdf parsing of scientific papers (eg. using something like GROBID, [[https://github.com/kermitt2/grobid]])
- Refine pdf text chunking (page breaks, references and metainformation, Figures?)
- +Add pdf uploader feature (fix compatibility to text reader and documents display)+
- improve knowledge graph visualization. (more than python necessary?)
- Add model selector
